### ISSUE TITLE
Where to download Bloomberg C++ SDK version 3.9 or later

### ISSUE THREAD

**Issue by r2123b** [msitt/blpapi-python#1]
I went to the [Bloomberg website](https://www.bloomberg.com/professional/support/api-library/). However, I cannot find where to download Bloomberg C++ SDK version 3.9 in API OS X section. Why?

**Comment by msitt** [comment]
You should contact Bloomberg support about getting the correct versions of the libraries.

**Comment by r2123b** [comment]
Have you already gotten the package of Bloomberg C++ SDK version 3.9?
